### ISSUE TITLE
Example authorization code request fails

### ISSUE THREAD

**Issue by drinkingcoffee** [adplabs/adp-connection-php#2]
Trying to create an authorization code connection in the sample application fails with: 

Mismatching redirect_uri. Given: 'http://localhost:8889/callback'

Are the example credentials no longer valid?

**Comment by ADPMarketplace** [comment]
Hi,

The redirection url was updated to some other value in the internal configurations which was causing this issue. We updated the redirect_uri back to the old one which resolves this issue. Please try now and let us know if you see any issues.

Thanks,
Reddaiah Challa
