### ISSUE TITLE
Communication Error, Status60 SSL Cert problem: self signed cert in cert chain

### ISSUE THREAD

**Issue by Jeremy4545** [adplabs/adp-connection-php#4]
Just installed adp-connection-php and everything was good until I tried to log in using Authorization Code,
MKPLDEMO,marketplace1.

I have downloaded the cacert.pem and set curl.cainfo=C:/cacert.pem in php.ini with no luck.

**Comment by Carpesimia** [comment]
Can you share the issue you are having?  Is there an error message?

**Comment by Carpesimia** [comment]
Jeremy, take a look at the #2 issue in this project.  It deals with the same issue you are having, with a number of links to assist you.  Here's a link for your convenience:

https://github.com/adplabs/adp-connection-php/issues/3
