### ISSUE TITLE
i am new to ADP.

### ISSUE THREAD

**Issue by SatishDanda** [adplabs/adp-connection-php#5]
where can i found 
  'grantType'             => 'client_credentials',
        'clientID'              => '88a73992-07f2-4714-ab4b-de782acd9c4d',
        'clientSecret'          => 'a130adb7-aa51-49ac-9d02-0d4036b63541',
        'sslCertPath'           => $ADP_CERTFILE,
        'sslKeyPath'            => $ADP_KEYFILE,
        'tokenServerURL'        => $ADP_APIROOT

these details. in runpayroll.adp.com

**Comment by ADPMarketplacePHP** [comment]
Please reach out to your integration specialist.  They will assist in getting you set up with the proper credentials.
