### ISSUE TITLE
php connection question

### ISSUE THREAD

**Issue by bdonathan** [adplabs/adp-connection-php#7]
Need a little help with the actual api pull. I have the client credentials connection setup successfully using the example provided, but not sure what to do next. I just need the job requisition endpoint (https://api.adp.com/staffing/v1/job-requisitions) output array in php - thanks in advance for the assistance!

**Comment by bdonathan** [comment]
I'm receiving the Bearer token, but I'm not sure if I'm sending it to the Authorization header correctly. in my php I have:
`$auth = "Authorization: Bearer " . $bearertoken;
            $curl = curl_init();

            curl_setopt_array($curl, array(
              CURLOPT_URL => "https://api.adp.com/staffing/v1/job-requisitions",
              CURLOPT_RETURNTRANSFER => true,
              CURLOPT_TIMEOUT => 30,
              CURLOPT_HTTP_VERSION => CURL_HTTP_VERSION_1_1,
              CURLOPT_CUSTOMREQUEST => "GET",
              CURLOPT_HTTPHEADER => array(
                "Content-Type: application/json",
                $auth
              ),
            ));

            $response = curl_exec($curl);
            $err = curl_error($curl);

            curl_close($curl);

            $response = json_decode($response, true);
            var_dump($response);`

I'm getting "Request did not provide the required two-way TLS certificate." response

**Comment by marianorenteria** [comment]
I think you are missing the certificates that need to be sent, this is how we have used the demographics call.
```
$urlEmployees = "https://api.adp.com/hr/v2/worker-demographics"

$curlEmployees = curl_init($urlEmployees);
curl_setopt($curlEmployees, CURLOPT_VERBOSE, '1'); 
curl_setopt($curlEmployees, CURLOPT_SSLCERT, './thisIsAPem.pem'); 
curl_setopt($curlEmployees, CURLOPT_SSLKEY, './thisIsAKey.key');
curl_setopt($curlEmployees, CURLOPT_KEYPASSWD, 'notputtingthishere');
curl_setopt($curlEmployees, CURLOPT_RETURNTRANSFER, true);
curl_setopt($curlEmployees, CURLOPT_USERAGENT, "adp-connection-php/1.0.1");
curl_setopt($curlEmployees, CURLOPT_HTTPHEADER, array(
'If-None-Match: none'
));
```

**Comment by bdonathan** [comment]
Thank you so much @marianorenteria - I added the cert and key as you recommended and at least now I'm getting a "Null" response instead of the error. I was expecting to get the json back though...   Any thoughts on that? I really really appreciate the help!

**Comment by marianorenteria** [comment]
@bdonathan, so to confirm... the steps you need to follow should be the following:

1. Obtain Authorization token using 
```
        $params = array(
            "grant_type" => "client_credentials"
        );
        
        $postdata = http_build_query($params, '', '&');
        
        $curl = curl_init('https://api.adp.com/auth/oauth/v2/token');
        curl_setopt($curl, CURLOPT_VERBOSE, '1');
        curl_setopt($curl, CURLOPT_SSLCERT, './certs/thisIsAPem.pem'); 
        curl_setopt($curl, CURLOPT_SSLKEY, './certs/thisIsAKey.key');
        curl_setopt($curl, CURLOPT_USERPWD, $adpClientId. ":" . $adpClientSecret);
        curl_setopt($curl, CURLOPT_KEYPASSWD, 'password');
        curl_setopt($curl, CURLOPT_RETURNTRANSFER, true);
        curl_setopt($curl, CURLOPT_POST, true);
        curl_setopt($curl, CURLOPT_POSTFIELDS, $postdata);
        curl_setopt($curl, CURLOPT_USERAGENT, "adp-connection-php/1.0.1");

        $curlJsonData = curl_exec($curl);
        // Decode Json
        $curlJsonDecoded = json_decode($curlJsonData);
        // Curl Status
        $curlStatus = curl_getinfo($curl, CURLINFO_HTTP_CODE);
        
        if ($curlStatus != 200) {
            
            if (curl_errno($curl) != 0) {
                // @codeCoverageIgnoreStart
                throw new \Exception("Communication Error" . curl_error($curl));
                return;
                // @codeCoverageIgnoreEnd
            } else {
                // @codeCoverageIgnoreStart
                throw new \Exception($curlJsonDecoded->error . $curlStatus . $curlJsonData);
                return;
                // @codeCoverageIgnoreEnd
            }
        } else {
            // print_r($curlJsonDecoded);
            
            // Fill in the access token property
            // $accessBearerToken = $curlJsonDecoded->access_token; << THIS is the token
            // $tokenExpiration = $curlJsonDecoded->expires_in + time();
         }
```

2. Use the token to query information
```
$urlEmployees = "https://api.adp.com/hr/v2/worker-demographics?access_token".$accessBearerToken;

$curlEmployees = curl_init($urlEmployees);
curl_setopt($curlEmployees, CURLOPT_VERBOSE, '1'); 
curl_setopt($curlEmployees, CURLOPT_SSLCERT, './thisIsAPem.pem'); 
curl_setopt($curlEmployees, CURLOPT_SSLKEY, './thisIsAKey.key');
curl_setopt($curlEmployees, CURLOPT_KEYPASSWD, 'notputtingthishere');
curl_setopt($curlEmployees, CURLOPT_RETURNTRANSFER, true);
curl_setopt($curlEmployees, CURLOPT_USERAGENT, "adp-connection-php/1.0.1");
curl_setopt($curlEmployees, CURLOPT_HTTPHEADER, array(
'If-None-Match: none'
));

$workersCurlResult = curl_exec($curlEmployees);
$curlWorkersStatus = curl_getinfo($curlEmployees, 

if ($curlWorkersStatus == 200) {
    $workersCurlResult = json_decode($workersCurlResult);
    //Begin decoding
}
```

I don't know why does the ADP Dev document doesn't mention the `access_token` as a GET parameter... but I hope this works for you.

**Comment by bdonathan** [comment]
@marianorenteria - thanks again for helping me with all this.
So it turned out that it was a directory issue with sending the cert and key files. Once I figured that out, I was able to get the api response.

Now my issue with the jobs requisition endpoint is the 20 item limit. According to the documentation is say that pagination is available like this:
https://api.adp.com/staffing/v1/job-requisitions?$top=20&$skip=0 - first 0-20 records
https://api.adp.com/staffing/v1/job-requisitions?$top=20&$skip=20 - next 21-40 records
and so on...

I'm having trouble adding those filters to the CURLOPT_URL... the "?" seems to be escaping the rest. My end goal is to get ALL the job records (there are only 29) listed - so even if I have to make two api requests and combine them, I'm good with that. Any thoughts?

**Comment by marianorenteria** [comment]
@bdonathan , sorry for the late reply, I've access to the Worker Demographics, and the pagination parameters are `limit` and `offset`.

And we use it like this:
- `/hr/v2/worker-demographics?token=xdft&offset=1&limit=100`  first 100 records
- `/hr/v2/worker-demographics?token=xdft&offset=101&limit=100`  second batch of 100 records

Hope that helps
